### ISSUE TITLE
Double Flush

### ISSUE THREAD

**Issue by zebulonj** [statsd/statsd#685] opened 2019-09-27 23:30 UTC
With the console backend enabled on, with the reference (example) config, I'm seeing a double-flush every 30 seconds (every third flush on a 20-second interval).

```
Flushing stats at  Fri Sep 27 2019 23:29:46 GMT+0000 (Coordinated Universal Time)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: { 'statsd.timestamp_lag': 0 },
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
Flushing stats at  Fri Sep 27 2019 23:29:46 GMT+0000 (Coordinated Universal Time)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: { 'statsd.timestamp_lag': -10 },
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
```

See the related issue on the Graphite project: https://github.com/graphite-project/docker-graphite-statsd/issues/52

**Comment by zebulonj** [comment] 2019-09-27 23:40
Interesting...

This only occurs on the Dockerized version. I've cloned this repository, and when running outside Docker, I don't see this. Will investigate further.

**Comment by BlueHatbRit** [comment] 2019-10-21 13:38
Hi @zebulonj, did you ever come to a conclusion on this?

**Comment by zebulonj** [comment] 2019-10-21 14:05
Only that it is consistently reproducible (anytime you dockerize statsd) and I can’t figure out why. I’ve stopped using statsd because of it.

**Comment by zebulonj** [comment] 2019-10-21 19:23
I first observed this in the published Graphite container (which includes `statsd`). I've since confirmed that it also occurs in the published, stand-alone `statsd` container, and I've also observed in a self-built container. The description that opens this issue is based on the published `statsd` published container. Just add the console backend to the config and watch the timestamps on the flushes that show in the console output.

**Comment by BlueHatbRit** [comment] 2019-10-21 19:33
Thanks, that should be enough for me to find it by the sounds of things!

**Comment by BlueHatbRit** [comment] 2019-10-24 13:22
Well I've managed to recreate this, seems I've not used the statsd docker image enough as this is pretty noticable with the console backend.

I've had a brief look and I can see it's likely something to do with our `flushMetrics` timed looping. The fact that this only happens in Docker makes me think this _could_ be a node issue since we just use `setTimeout` and it acts normally outside of docker.

I'll see if I can get a smaller code example to reproduce the issue. That should either uncover whether it's our issue, or whether it's a node issue.

**Comment by zebulonj** [comment] 2019-10-24 14:21
Appreciate you digging. I may have some time tomorrow or early next week to see if I can reproduce a similar result outside the context on statsd (to test the theory that it may be a Node issue). I've reviewed the code (superficially) and don't see any obvious reasons that this should behave differently in Docker.

**Comment by BlueHatbRit** [comment] 2019-10-28 10:22
I've so far been unsuccessful in pinning this down. I ran node in debug mode (in docker) and the issue was happening, as soon as I started using break points it stopped happening. I'm going to log out the stack trace for each call and see what that does.

**Comment by BlueHatbRit** [comment] 2019-11-07 10:19
I created a little script which helps to demo this problem while I attempt to figure out the best way to fix it. I've tried a few approaches but most of that is resulting in time slipping so far. Here's the script as it is right now for anyone that wants to give it a crack.

```!javascript
const startupTime = 1572619574;

const sets = [
  //.   1572619574000
  {now: 1572619574374, startup_time: startupTime},
  {now: 1572619583974, startup_time: startupTime},
  {now: 1572619584010, startup_time: startupTime},
  {now: 1572619594014, startup_time: startupTime},
  {now: 1572619604016, startup_time: startupTime},
  {now: 1572619613979, startup_time: startupTime},
  {now: 1572619614006, startup_time: startupTime},
  {now: 1572619624012, startup_time: startupTime},
  {now: 1572619634012, startup_time: startupTime},
  {now: 1572619643974, startup_time: startupTime},
  {now: 1572619644000, startup_time: startupTime}
];

const interval = 10000;

console.log('starting run with interval:', interval);

sets.forEach(set => {
  const deltaTime = set.now - (set.startup_time * 1000);
  const timeout = interval - (deltaTime % interval);
  console.log(deltaTime, interval - deltaTime, timeout);
});
```

**Comment by aonischenko** [comment] 2020-01-09 18:33
@BlueHatbRit Is there any progress with this bug?
If you still look for a workaround, think changing your example like this might help:
```
sets.forEach(set => {
    const deltaTime = set.now - set.startup_time * 1000;
    const timeout = interval - (deltaTime % interval);

    const attempt = Math.round(deltaTime / interval) + 1;
    const fixedTimeout = (set.startup_time * 1000 + attempt * interval) - set.now;

    console.log(attempt, deltaTime, interval - deltaTime, timeout, fixedTimeout);
});

**Comment by BlueHatbRit** [comment] 2020-01-09 23:21
Hi there @aonischenko, yeah I just took a break as I was struggling to make progress. That looks promising! I'll give that a crack tomorrow or Monday and see what it produces. Thanks so much for the concise contribution to the issue. I'll get back to you as soon as I can!

**Comment by BlueHatbRit** [comment] 2020-02-25 11:07
It looks like @aonischenko's solution worked 🎊 it was so simple I don't know how I didn't arrive at that.

I'm letting a long running test tick over today on a container locally and after a few hours I'll check there hasn't been any slippage or double ticks. If that's the case then I'll get this merged and a deployment made today.

**Comment by BlueHatbRit** [comment] 2020-02-26 09:58
This has gone out as 0.8.6, thanks for your help everyone 🚀

**Closed by BlueHatbRit** 2020-02-26 09:58 UTC
Labels: bug
